---
title: ''
output: html_document
---


# Heart Data
Heart Disease UCI dataset from https://archive.ics.uci.edu/ml/datasets/Heart+Disease

# Description  
This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them. In particular, the Cleveland database is the only one that has been used by ML researchers to this date. The "goal" field refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4.

# Variables  
* age = age in years 
* sex = (1 = male; 0 = female)
* cp = Chest Pain Type
* trestbps = resting blood pressure (in mm Hg on admission to the hospital)
* chol = serum cholesterol in mg/dl 
* fbs = (fasting blood sugar &gt; 120 mg/dl) (1 = true; 0 = false)
* restecg = resting electrocardiographic results (values 0,1,2) 
* thalach = maximum heart rate achieved 
* exang = exercise induced angina  
* oldpeak = ST depression induced by exercise relative to rest 
* slope = the slope of the peak exercise ST segment 
* ca = number of major vessels (0-3) colored by flourosopy 
* thal: 3 = normal; 6 = fixed defect; 7 = reversable defect
* target = presence (1) or absence (0) of heart disease

# Additional information  
Creators:

* Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
* University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
* University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
* V.A. Medical Center, Long Beach and Cleveland Clinic Foundation: Robert Detrano, M.D., Ph.D.


[Dataset link](https://www.kaggle.com/ronitf/heart-disease-uci)  